model_args:
  model_name_or_path: "hotchpotch/japanese-reranker-xsmall-v2"
  mode: "reranking_pruning"

data_args:
  dataset_name: "hotchpotch/wip-msmarco-context-relevance"
  subset: "msmarco-ja-small"
  teacher_column: "teacher_scores.japanese-reranker-xsmall-v2"
  filter_zero_relevance_max_items: 4
  filter_keep_first_item: true  # 先頭一件を必ず残す

training_args:
  output_dir: "./tmp/test_keep_first"
  num_train_epochs: 0.01
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 4
  learning_rate: 5.0e-5
  report_to: []